name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: 24.1
          elixir-version: 1.13
      - run: mix deps.get
      - run: mix format --check-formatted

  test:
    name: OTP ${{matrix.erlang}} / Elixir ${{matrix.elixir}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - erlang: 24.1
            elixir: 1.13
          - erlang: 24.0.1
            elixir: 1.12.1
          - erlang: 23.3
            elixir: 1.11.4
          - erlang: 23.3
            elixir: 1.10.4

    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          otp-version: ${{matrix.erlang}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
